# Generated by Django 5.1.3 on 2025-01-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.IntegerField(choices=[(1, 'Wellfound'), (2, 'Remoteok'), (3, 'Remotive'), (4, 'Weworkremotely'), (5, 'Jobsindev'), (6, 'Stackoverflow'), (7, 'Github'), (8, 'Angellist'), (9, 'Landingjobs'), (10, 'Workingnomads'), (11, 'Remotely')])),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('remote', models.BooleanField()),
                ('experience', models.CharField(max_length=100)),
                ('visa_sponsorship', models.BooleanField()),
                ('hires_remotely_in', models.CharField(max_length=100)),
                ('relocation', models.CharField(max_length=100)),
                ('hiring_contacts', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
