# Generated by Django 4.2.7 on 2024-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='financing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='logo',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
    ]
