# Generated by Django 4.2.7 on 2024-03-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_financing_projects_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='financing',
            new_name='raised',
        ),
    ]
